// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeyoDEjrd49X_Ivu1bDUGYHni0G1_JEHg',
    appId: '1:401953104200:web:bc445501c47a46e811537d',
    messagingSenderId: '401953104200',
    projectId: 'todos-3b767',
    authDomain: 'todos-3b767.firebaseapp.com',
    storageBucket: 'todos-3b767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPXQmxVReyBk5yu_VFlY90A36WjloCxJI',
    appId: '1:401953104200:android:09a4ed17e6f9293311537d',
    messagingSenderId: '401953104200',
    projectId: 'todos-3b767',
    storageBucket: 'todos-3b767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZ9KzuVtMRtZrHjqOuXDfqJEk6XI4KcA',
    appId: '1:401953104200:ios:99ee787d4c1c394411537d',
    messagingSenderId: '401953104200',
    projectId: 'todos-3b767',
    storageBucket: 'todos-3b767.appspot.com',
    iosClientId: '401953104200-9unq5l3el0ugff0mtta0sm2eekrjpvfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZ9KzuVtMRtZrHjqOuXDfqJEk6XI4KcA',
    appId: '1:401953104200:ios:6672e698bad3e0b511537d',
    messagingSenderId: '401953104200',
    projectId: 'todos-3b767',
    storageBucket: 'todos-3b767.appspot.com',
    iosClientId: '401953104200-b7hcrjrku70gcpn8pcuhhj8usklumfrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todos.RunnerTests',
  );
}
